### ISSUE TITLE
Can't get driver work

### ISSUE THREAD

**Issue by bubnenkoff** [gurzgri/red-odbc#1]
Hi! I do not know are you present in red gitter. So I copy-past problem here:
I decided to try this driver. I placed odbc.red and odbc.reds in app.red folder.
app.red:
```
Red []
#import %odbc.red

drivers: odbc-drivers
print drivers
```
then tried to compile it and got error:
```
*** Compilation Error: undefined word odbc-drivers
*** in file: D:\code\odbc_test\app.red
*** near: [odbc-drivers
    print drivers
]
```

**Comment by gurzgri** [comment]
The prepocesser directive is #include, not #import.

**Comment by gurzgri** [comment]
Fixed the README.
