### ISSUE TITLE
Compilation Error: undefined symbol: red/string/load-in

### ISSUE THREAD

**Issue by bubnenkoff** [gurzgri/red-odbc#2]
Hi! I am trying to compile minimal app:
```
Red []

#include %odbc.red

print system/schemes/odbc/drivers
```
I am getting an error:
```
D:\code\test\red-odbc-master>c:\red\red.exe -c app.red

-=== Red Compiler 0.6.4 ===-

Compiling D:\code\test\red-odbc-master\app.red ...
Compiling libRedRT...
...compilation time : 1741 ms

Compiling to native code...
...compilation time : 58475 ms
...global words     : 22931 (69.71%)
...linking time     : 718 ms
...output file size : 1311744 bytes
...output file      : D:\code\test\red-odbc-master\libRedRT.dll

...compilation time : 1003 ms

Target: MSDOS

Compiling to native code...
*** Compilation Error: undefined symbol: red/string/load-in
*** in file: %/D/code/test/red-odbc-master/odbc.red
*** in function: exec/diagnose-error
*** at line: 3364
*** near: [
    string/load-in as c-string! state 5 errors UTF-16LE
    integer/make-in
]
```

red:
```
>> about
Red 0.6.4 for Windows built 3-Feb-2022/20:16:35+03:00  commit #fbdf84d
```

**Comment by gurzgri** [comment]
Hi Dmitry,

don't try to get this about-to-be-abandoned repo gurzgri/red-odbc working, try https://github.com/gurzgri/red/tree/odbc  instead, I've made some huge improvements there. 

Clone the odbc branch and compile a red cli console or gui console instead, then you can try out odbc:// scheme interactively in the red console and in interpreted scripts. See the documentation in https://github.com/gurzgri/red/blob/odbc/environment/schemes/odbc.md on how to use it. 

Compare pull request https://github.com/red/red/pull/5072, too, I'd love to get some feedback on this there.

Cheers,
Christian
