### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by GiuseppeChillemi** [gurzgri/red-odbc#3]
I am trying RED-ODBC
With the latest version I receive the following error: 

Compiling C:\Users\Administrator\Dropbox\Svi\scripts\red-odbc.red ...
...using libRedRT built on 11-Mar-2022/21:11:14
...compilation time : 2186 ms

Target: MSDOS

Compiling to native code...
*** Compilation Error: undefined symbol: red/string/load-in
*** in file: %/C/Users/Administrator/Dropbox/Svi/red-odbc-master/odbc.red
*** in function: exec/diagnose-error
*** at line: 3364
*** near: [
    string/load-in as c-string! state 5 errors UTF-16LE
    integer/make-in
]

script is really simple:

```
#include %../red-odbc-master/odbc.red

probe system/schemes/odbc/drivers
probe system/schemes/odbc/sources
```

**Comment by gurzgri** [comment]
Don't try to get this about-to-be-abandoned repo gurzgri/red-odbc working, try pull request https://github.com/red/red/pull/5072 from https://github.com/gurzgri/red instead. Clone the odbc branch and compile a red cli console or gui console instead, then you can try out odbc:// scheme interactively in the red console and in interpreted scripts. See the documentation in https://github.com/gurzgri/red/blob/odbc/environment/schemes/odbc.md on how to use it.

**Comment by GiuseppeChillemi** [comment]
If I figure it out how to download from a specific pull request... I don't know how to do it!

**Comment by gurzgri** [comment]
Just `git clone --branch odbc https://github.com/gurzgri/red.git odbc-test` and then compile with `do/args %red.r "-r %environment/console/CLI/console.red"`. In case you don't know what this means, see https://github.com/red/red#running-red-from-the-sources-for-contributors for more info on Red's compilation process.

**Comment by bubnenkoff** [comment]
@gurzgri Could you explain what stop from merging?

    Red need some improvement before it can be done?
    Red do not need in out of the box?
    odbc driver need some improving?
    ...

I am asking to better understand situation to be able to plan the job.

**Comment by bubnenkoff** [comment]
@gurzgri thanks!
What I should use in this string: `<DRIVERNAME>` ?
Should I setup ODBC connection in Windows Control Panel before? And is it's possible to connect to x64 PostgreSQL instance?
